// src/lib/components/opener/Subheadings.svelte
<script lang="ts">
	interface LinkItem {
		text: string;
		clickHandler: () => void;
	}

	const handleEmailClick = () => {
		console.log('Clicked email');
		window.location.href = 'mailto:joshuagyfung@gmail.com';
	};

	const handleGithubClick = () => {
		console.log('Clicked Github');
		window.open('https://github.com/JoshFung', '_blank');
	};

	const handleResumeClick = () => {
		console.log('Clicked resume');
		const JoshFungResume = '/JoshFungResume.pdf';
		window.open(JoshFungResume, '_blank');
	};

	const handleLinkedInClick = () => {
		console.log('Clicked LinkedIn');
		window.open('https://linkedin.com/in/joshfung/', '_blank');
	};

	let items: LinkItem[] = [
		{ text: 'Email', clickHandler: handleEmailClick },
		{ text: 'Github', clickHandler: handleGithubClick },
		{ text: 'Resume', clickHandler: handleResumeClick },
		{ text: 'LinkedIn', clickHandler: handleLinkedInClick }
	];
</script>

<div
	class="flex flex-col flex-1 justify-evenly items-start px-4 xs:px-6 sm:px-8 pt-4 xs:pt-6 sm:pt-8"
>
	{#each items as item (item.text)}
		<button
			on:click={item.clickHandler}
			class="text-isabelline font-switzer font-medium text-lg xs:text-2xl sm:text-3xl"
		>
			{item.text}
		</button>
	{/each}
</div>

<style>
</style>

// src/components/Subheadings.tsx

interface LinkItem {
  text: string;
  clickHandler: () => void;
}

function Subheadings() {
  const handleEmailClick = () => {
    console.log("Email clicked");
    window.location.href = "mailto:joshuagyfung@gmail.com";
  };

  const handleGithubClick = () => {
    console.log("GitHub clicked");
    window.open("https://github.com/JoshFung", "_blank");
  };

  const handleResumeClick = () => {
    console.log("Resume clicked");
    window.open("/JoshuaFungResume.pdf", "_blank");
  };

  const handleLinkedInClick = () => {
    console.log("LinkedIn clicked");
    window.open("https://linkedin.com/in/joshfung/", "_blank");
  };

  const links: LinkItem[] = [
    { text: "Email", clickHandler: handleEmailClick },
    { text: "GitHub", clickHandler: handleGithubClick },
    { text: "Resume", clickHandler: handleResumeClick },
    { text: "LinkedIn", clickHandler: handleLinkedInClick },
  ];

  return (
    <div className="flex flex-row justify-between">
      {links.map((item: LinkItem) => (
        <button
          key={item.text}
          onClick={item.clickHandler}
          className="text-isabelline font-jakarta font-regular text-2xs sm:text-2xl"
        >
          {item.text}
        </button>
      ))}
    </div>
  )
}

export default Subheadings;
